// routes namer akta folder banalam jekhane sob routes thakbe......
// routes folder er modhe user.js baniyechi jekhane sob user routes thakbe.....abar jodi kono products namer kono routes thake tahole routes folder er modhe products.js baniye sob products routes ote rakbo....... 
import express from "express";
import { getalluser, createnewuser, getparams, getdynamicurl, getdynamicurlput, getdynamicurldelete } from "../controllers/user.js";// controllers folder er user.js er sob function gulo import korlam....


const router = express.Router(); // jemon app banatam.....temon akhane router banalam....jemon app. likhe (get,post,put,delete) access korte partam temon router. likhe ogulo same vabe use korte parbo.......


// tolay sob user routes gulor url er modhe "/users" common.....tai akhane sob kota routes a "/users" na diye........app.js file er modhe jekhane midle ware er modhe ai routes gulo use korechi sekhane akta prefix add kore dobo "/users" namer.....tahole ar akhane sob routes gulo te "/users" dite hobe na......

router.get("/all",getalluser); // controllers folder er user.js er function use korlam...

router.post("/new",createnewuser); // controllers folder er user.js er function use korlam...

router.get("/params",getparams); // controllers folder er user.js er function use korlam...

// tolay 3 te routes aki ache kintu method ta alada....tai arokom na likhe ami ak line a likte pari
router.route("/userid/:id").get(getdynamicurl).put(getdynamicurlput).delete(getdynamicurldelete);

// router.get("/userid/:id", getdynamicurl); // controllers folder er user.js er function use korlam... 

// router.put("/userid/:id", getdynamicurlput); // controllers folder er user.js er function use korlam... 

// router.delete("/userid/:id", getdynamicurldelete); // controllers folder er user.js er function use korlam... 

export default router; // akhane router take export korechi....kintu main file app.js a ata use korte hobe tai app.js a import korte hobe....app.js er midle ware a ata ke use korte hobe....